-- Database Schema Update for Mitti Mitra
-- Redefined tables to match new ML models and data requirements

-- 1. Crop Prediction History
CREATE TABLE IF NOT EXISTS crop_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    device_id TEXT DEFAULT 'web_client',
    
    -- Inputs
    nitrogen NUMERIC(6, 2),
    phosphorus NUMERIC(6, 2),
    potassium NUMERIC(6, 2),
    ph NUMERIC(4, 2),
    temperature NUMERIC(5, 2),
    humidity NUMERIC(5, 2),
    rainfall NUMERIC(6, 2),
    city TEXT,
    
    -- Output
    predicted_crop TEXT,
    confidence NUMERIC(5, 2), -- 0.00 to 1.00
    translated_crop TEXT      -- Local language name if applicable
);

-- 2. Yield Prediction History
CREATE TABLE IF NOT EXISTS yield_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Inputs
    state TEXT,
    district TEXT,
    crop TEXT,
    season TEXT,
    annual_rainfall NUMERIC(7, 2),
    fertilizer_usage NUMERIC(7, 2),
    pesticide_usage NUMERIC(7, 2),
    soil_type TEXT,
    
    -- Output
    predicted_yield NUMERIC(7, 2) -- tons/hectare
);

-- 3. Fertilizer Recommendation History
CREATE TABLE IF NOT EXISTS fertilizer_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Inputs
    nitrogen NUMERIC(6, 2),
    phosphorus NUMERIC(6, 2),
    potassium NUMERIC(6, 2),
    temperature NUMERIC(5, 2),
    humidity NUMERIC(5, 2),
    moisture NUMERIC(5, 2),
    soil_type TEXT,
    crop_type TEXT,
    
    -- Output
    recommended_fertilizer TEXT,
    translated_fertilizer TEXT,
    reasoning TEXT[] -- Array of explanation strings
);

-- Indexes for Analytics
CREATE INDEX IF NOT EXISTS idx_crop_pred_created ON crop_predictions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_yield_pred_created ON yield_predictions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fert_pred_created ON fertilizer_predictions(created_at DESC);
