-- Database Schema for Mitti Mitra

-- Create table for sensor readings
CREATE TABLE IF NOT EXISTS sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Device Identity
    device_id TEXT NOT NULL DEFAULT 'pi_01',
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    
    -- Environmental Data
    temperature NUMERIC(5, 2), -- Celsius
    humidity NUMERIC(5, 2),    -- Percentage
    rainfall NUMERIC(6, 2),    -- mm
    
    -- Soil Data
    ph NUMERIC(4, 2),          -- 0.0 to 14.0
    nitrogen NUMERIC(6, 2),    -- mg/kg
    phosphorus NUMERIC(6, 2),  -- mg/kg
    potassium NUMERIC(6, 2)    -- mg/kg
);

-- Index for faster time-based queries (e.g., getting latest reading)
CREATE INDEX IF NOT EXISTS idx_sensor_readings_timestamp ON sensor_readings (timestamp DESC);

-- Optional: Create a view for daily averages (if not handled by code)
CREATE OR REPLACE VIEW daily_averages AS
SELECT 
    date_trunc('day', timestamp) as day,
    AVG(temperature) as avg_temp,
    AVG(humidity) as avg_humidity,
    AVG(ph) as avg_ph,
    SUM(rainfall) as total_rain
FROM sensor_readings
GROUP BY 1
ORDER BY 1 DESC;
